In [1]:
import numpy as np

In [59]:
a = np.arange(9).reshape(3, 3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [60]:
a.shape, a.ndim, a.size, a.dtype, type(a)

((3, 3), 2, 9, dtype('int64'), numpy.ndarray)

In [61]:
a.reshape((-1, 1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [62]:
a.reshape((1, -1))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [7]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [53]:
x = np.array([1, 2, 4, 6])
print(x + 10)
print(x ** 2)
print(np.sum(x ** 2))

[11 12 14 16]
[ 1  4 16 36]
57


In [21]:
np.max(x), np.mean(x), np.std(x)

(6, 3.25, 1.920286436967152)

In [24]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
x[2:6]

array([2, 3, 4, 5])

In [26]:
x[-1]

9

In [27]:
a = np.array([4., 2.])
b = np.array([3., 8.])

np.vstack([a, b])

array([[4., 2.],
       [3., 8.]])

In [28]:
np.hstack([a, b])

array([4., 2., 3., 8.])

In [29]:
np.concatenate([a, b])

array([4., 2., 3., 8.])

In [32]:
x = np.arange(10)
y = x
y[0] = 100
x

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [33]:
x = np.arange(10)
y = x.copy()
y[0] = 100
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 10])
x.dot(y)

37

In [41]:
a = np.array([[0,0,0],
              [10,10,10],
              [20,20,20],
              [30,30,30]]) 
b = np.array([1,2,3])  

a + b   # broadcasting

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [48]:
np.ones(3) + np.ones(3)

array([2., 2., 2.])

In [49]:
np.ones((3,1)) + np.ones(3)
# Broadcasting mistakes can be tricky. Probably you didn't mean that

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [50]:
a.T

array([[ 0, 10, 20, 30],
       [ 0, 10, 20, 30],
       [ 0, 10, 20, 30]])

In [64]:
a = np.array([[1, 2],
              [2, 3]])

b = np.array([[4, 1],
              [2, 2]])

np.matmul(a, b)

array([[ 8,  5],
       [14,  8]])

In [66]:
res = a @ b
res

array([[ 8,  5],
       [14,  8]])

In [67]:
from numpy.linalg import inv
inv(res)

array([[-1.33333333,  0.83333333],
       [ 2.33333333, -1.33333333]])

In [69]:
inv(res).astype(np.int64)

array([[-1,  0],
       [ 2, -1]])